/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSearchMarkingRouteImport } from './routes/_authenticated/search-marking'
import { Route as AuthenticatedMarkingRouteImport } from './routes/_authenticated/marking'
import { Route as AuthenticatedManageStudentsRouteImport } from './routes/_authenticated/manage-students'
import { Route as AuthenticatedDateSelectionRouteImport } from './routes/_authenticated/date-selection'
import { Route as AuthenticatedAttendanceHistoryRouteImport } from './routes/_authenticated/attendance-history'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchMarkingRoute =
  AuthenticatedSearchMarkingRouteImport.update({
    id: '/search-marking',
    path: '/search-marking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarkingRoute = AuthenticatedMarkingRouteImport.update({
  id: '/marking',
  path: '/marking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManageStudentsRoute =
  AuthenticatedManageStudentsRouteImport.update({
    id: '/manage-students',
    path: '/manage-students',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDateSelectionRoute =
  AuthenticatedDateSelectionRouteImport.update({
    id: '/date-selection',
    path: '/date-selection',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceHistoryRoute =
  AuthenticatedAttendanceHistoryRouteImport.update({
    id: '/attendance-history',
    path: '/attendance-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/attendance-history': typeof AuthenticatedAttendanceHistoryRoute
  '/date-selection': typeof AuthenticatedDateSelectionRoute
  '/manage-students': typeof AuthenticatedManageStudentsRoute
  '/marking': typeof AuthenticatedMarkingRoute
  '/search-marking': typeof AuthenticatedSearchMarkingRoute
  '/': typeof AuthenticatedIndexRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/attendance-history': typeof AuthenticatedAttendanceHistoryRoute
  '/date-selection': typeof AuthenticatedDateSelectionRoute
  '/manage-students': typeof AuthenticatedManageStudentsRoute
  '/marking': typeof AuthenticatedMarkingRoute
  '/search-marking': typeof AuthenticatedSearchMarkingRoute
  '/': typeof AuthenticatedIndexRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/_authenticated/attendance-history': typeof AuthenticatedAttendanceHistoryRoute
  '/_authenticated/date-selection': typeof AuthenticatedDateSelectionRoute
  '/_authenticated/manage-students': typeof AuthenticatedManageStudentsRoute
  '/_authenticated/marking': typeof AuthenticatedMarkingRoute
  '/_authenticated/search-marking': typeof AuthenticatedSearchMarkingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dev-login'
    | '/login'
    | '/attendance-history'
    | '/date-selection'
    | '/manage-students'
    | '/marking'
    | '/search-marking'
    | '/'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev-login'
    | '/login'
    | '/attendance-history'
    | '/date-selection'
    | '/manage-students'
    | '/marking'
    | '/search-marking'
    | '/'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/dev-login'
    | '/login'
    | '/_authenticated/attendance-history'
    | '/_authenticated/date-selection'
    | '/_authenticated/manage-students'
    | '/_authenticated/marking'
    | '/_authenticated/search-marking'
    | '/_authenticated/'
    | '/_authenticated/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DevLoginRoute: typeof DevLoginRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search-marking': {
      id: '/_authenticated/search-marking'
      path: '/search-marking'
      fullPath: '/search-marking'
      preLoaderRoute: typeof AuthenticatedSearchMarkingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marking': {
      id: '/_authenticated/marking'
      path: '/marking'
      fullPath: '/marking'
      preLoaderRoute: typeof AuthenticatedMarkingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage-students': {
      id: '/_authenticated/manage-students'
      path: '/manage-students'
      fullPath: '/manage-students'
      preLoaderRoute: typeof AuthenticatedManageStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/date-selection': {
      id: '/_authenticated/date-selection'
      path: '/date-selection'
      fullPath: '/date-selection'
      preLoaderRoute: typeof AuthenticatedDateSelectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance-history': {
      id: '/_authenticated/attendance-history'
      path: '/attendance-history'
      fullPath: '/attendance-history'
      preLoaderRoute: typeof AuthenticatedAttendanceHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAttendanceHistoryRoute: typeof AuthenticatedAttendanceHistoryRoute
  AuthenticatedDateSelectionRoute: typeof AuthenticatedDateSelectionRoute
  AuthenticatedManageStudentsRoute: typeof AuthenticatedManageStudentsRoute
  AuthenticatedMarkingRoute: typeof AuthenticatedMarkingRoute
  AuthenticatedSearchMarkingRoute: typeof AuthenticatedSearchMarkingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendanceHistoryRoute: AuthenticatedAttendanceHistoryRoute,
  AuthenticatedDateSelectionRoute: AuthenticatedDateSelectionRoute,
  AuthenticatedManageStudentsRoute: AuthenticatedManageStudentsRoute,
  AuthenticatedMarkingRoute: AuthenticatedMarkingRoute,
  AuthenticatedSearchMarkingRoute: AuthenticatedSearchMarkingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DevLoginRoute: DevLoginRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
