/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarkingRouteImport } from './routes/marking'
import { Route as DateSelectionRouteImport } from './routes/date-selection'
import { Route as IndexRouteImport } from './routes/index'

const MarkingRoute = MarkingRouteImport.update({
  id: '/marking',
  path: '/marking',
  getParentRoute: () => rootRouteImport,
} as any)
const DateSelectionRoute = DateSelectionRouteImport.update({
  id: '/date-selection',
  path: '/date-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/date-selection': typeof DateSelectionRoute
  '/marking': typeof MarkingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/date-selection': typeof DateSelectionRoute
  '/marking': typeof MarkingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/date-selection': typeof DateSelectionRoute
  '/marking': typeof MarkingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/date-selection' | '/marking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/date-selection' | '/marking'
  id: '__root__' | '/' | '/date-selection' | '/marking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DateSelectionRoute: typeof DateSelectionRoute
  MarkingRoute: typeof MarkingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marking': {
      id: '/marking'
      path: '/marking'
      fullPath: '/marking'
      preLoaderRoute: typeof MarkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-selection': {
      id: '/date-selection'
      path: '/date-selection'
      fullPath: '/date-selection'
      preLoaderRoute: typeof DateSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DateSelectionRoute: DateSelectionRoute,
  MarkingRoute: MarkingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
